In [1]:
import pandas as pd

In [2]:
original = pd.read_csv('data/trace_original/2014_07.csv')
APlocations = pd.read_csv('data/traceset1/APlocations.csv')
preprocessed = pd.read_csv('data/trace_by_ID/19.csv')

In [ ]:
original[:5]

In [ ]:
APlocations[:5]

In [ ]:
preprocessed[:5]

In [7]:
preprocessed = pd.read_csv('data/trace_by_ID/10.csv')

In [8]:
preprocessed[:15]

sec  ID  x_coordinate(m)  y_coordinate(m)  AP_ID
0     113  10            21534            32313     21
1   27727  10            21728            32711    141
2   46175  10            21728            32711    142
3   27931  10            21613            32759    206
4   27992  10            21613            32759    204
5   46157  10            21728            32711    144
6   27665  10            21804            32683     53
7   27985  10            21613            32759    193
8   45590  10            21763            32993    458
9   28191  10            21408            33024    652
10  45383  10            21408            33024    652
11  28238  10            21399            33054    679
12  45323  10            21399            33054    679
13  28320  10            21399            33054    689
14  28627  10            21399            33054    689

In [3]:
import neighborDiscovery
import queue
import numpy as np

In [4]:
nd = neighborDiscovery.neighborDiscovery()
storage = queue.Queue()

In [23]:
storage.put(28627)

In [24]:
storage.qsize()

15

In [27]:
for i in range(storage.qsize()):
    a = storage.get()
    print(a)
    storage.put(a)

113
27727
46175
27931
27992
46157
27665
27985
45590
28191
45383
28238
45323
28320
28627


In [28]:
patterns=[]
t_list = []
qsize = storage.qsize()
for i in range(3):
    t_list.append(storage.get())

for i in range(qsize-3):
    patterns.append(np.array(t_list))
    storage.put(t_list[0])
    t_list = t_list[1:]
    t_list.append(storage.get())

for i in range(3):
    storage.put(t_list[i])

patterns.append(np.array(t_list))

In [29]:
t_list

[45323, 28320, 28627]

In [30]:
patterns

[array([  113, 27727, 46175]),
 array([27727, 46175, 27931]),
 array([46175, 27931, 27992]),
 array([27931, 27992, 46157]),
 array([27992, 46157, 27665]),
 array([46157, 27665, 27985]),
 array([27665, 27985, 45590]),
 array([27985, 45590, 28191]),
 array([45590, 28191, 45383]),
 array([28191, 45383, 28238]),
 array([45383, 28238, 45323]),
 array([28238, 45323, 28320]),
 array([45323, 28320, 28627])]

In [33]:
predicted = nd.ContactPrediction(storage, 1000)

In [34]:
predicted

[27798.0]

In [49]:
predicted = []
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,27798, 1200)
print(case_type, ":",duty_cycle)

1 : 8


In [50]:
predicted = [27798.0]
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,27798, 1200)
print(case_type, ":",duty_cycle)

2 : 20.0


In [55]:
predicted = [27798.0]
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,10000, 1200)
print(case_type, ":",duty_cycle)

4 : 2


In [54]:
predicted = [20000, 30000]
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,25000, 5000)
print(case_type, ":",duty_cycle)

3 : 8.0
