In [1]:
import pandas as pd

In [2]:
original = pd.read_csv('../data/trace_original/2014_07.csv')
APlocations = pd.read_csv('../data/traceset1/APlocations.csv')
preprocessed = pd.read_csv('../data/trace_by_ID/19.csv')

In [3]:
original[:5]

timestamp                                    client          AP
0  2014-07-01 00:00:00  f64443953de139ed7f06f8499de48d892d9d1a9c  Bldg23AP20
1  2014-07-01 00:00:03  a3a70736a03d6e74599d334d5f7a81ee84d0ffdd  Bldg46AP16
2  2014-07-01 00:00:05  b83a4f6bca9b6df3993fa49903c34eaa76fbc8b5  Bldg11AP14
3  2014-07-01 00:00:10  e46ebcb72cdedbe6daa4de7ddac1252ff4d946db   Bldg4AP11
4  2014-07-01 00:00:11  a4c3999bb38fb833672dc9f0b7213e1e9b80e473   Bldg4AP11

In [4]:
APlocations[:5]

AP  x_coordinate(m)  y_coordinate(m)  floor  AP_ID
0  Bldg1AP1            21534            32313      2      0
1  Bldg1AP2            21534            32313      2      1
2  Bldg1AP3            21534            32313      3      2
3  Bldg1AP4            21534            32313      3      3
4  Bldg1AP5            21534            32313      4      4

In [5]:
preprocessed[:5]

sec  ID  x_coordinate(m)  y_coordinate(m)  AP_ID
0   219  19            14356            39196   1066
1   388  19            14356            39196   1082
2   780  19            14356            39196   1082
3  1392  19            14356            39196   1082
4  1584  19            14356            39196   1082

In [22]:
preprocessed = pd.read_csv('../data/new_trace_by_ID/62767.csv',delimiter='\t',names=['sec','AP_id','x','y','date','CL_id'])

In [23]:
preprocessed[:15]

sec  AP_id      x      y        date  CL_id
0   48230     69  21804  32683  2014-09-01  62767
1   50029     69  21804  32683  2014-09-01  62767
2   51819     69  21804  32683  2014-09-01  62767
3   53619     69  21804  32683  2014-09-01  62767
4   54044    184  21836  32737  2014-09-01  62767
5   54096     57  21804  32683  2014-09-01  62767
6   54173     58  21804  32683  2014-09-01  62767
7   54276    170  21804  32683  2014-09-01  62767
8   54282     76  21728  32711  2014-09-01  62767
9   54305     62  21728  32711  2014-09-01  62767
10  33943     70  21804  32683  2014-09-02  62767
11  33945     70  21804  32683  2014-09-02  62767
12  34025     71  21804  32683  2014-09-02  62767
13  34034    184  21836  32737  2014-09-02  62767
14  34036     71  21804  32683  2014-09-02  62767

In [24]:
import neighborDiscovery
import queue
import numpy as np

In [56]:
nd = neighborDiscovery.neighborDiscovery()
storage = queue.Queue()

In [58]:
for i in range(80,160):
    storage.put(preprocessed.iloc[i,0])

In [59]:
storage.qsize()

80

In [41]:
for i in range(storage.qsize()):
    a = storage.get()
    print(a)
    storage.put(a)

48230
50029
51819
53619
54044
54096
54173
54276
54282
54305
33943
33945
34025
34034
34036
34193
34202
34212
34400
34410
34419
34428
34608
34617
34627
34711
34720
34729
34739
34779


In [60]:
patterns=[]
t_list = []
qsize = storage.qsize()
for i in range(3):
    t_list.append(storage.get())

for i in range(qsize-3):
    patterns.append(np.array(t_list))
    storage.put(t_list[0])
    t_list = t_list[1:]
    t_list.append(storage.get())

for i in range(3):
    storage.put(t_list[i])

patterns.append(np.array(t_list))

In [52]:
t_list

[37263, 37509, 37594]

In [61]:
patterns

[array([37665, 37758, 37762]),
 array([37758, 37762, 37772]),
 array([37762, 37772, 37781]),
 array([37772, 37781, 37821]),
 array([37781, 37821, 37861]),
 array([37821, 37861, 37870]),
 array([37861, 37870, 37879]),
 array([37870, 37879, 37919]),
 array([37879, 37919, 37928]),
 array([37919, 37928, 37947]),
 array([37928, 37947, 37966]),
 array([37947, 37966, 37987]),
 array([37966, 37987, 37996]),
 array([37987, 37996, 38006]),
 array([37996, 38006, 38046]),
 array([38006, 38046, 38055]),
 array([38046, 38055, 38095]),
 array([38055, 38095, 38135]),
 array([38095, 38135, 38230]),
 array([38135, 38230, 38239]),
 array([38230, 38239, 38245]),
 array([38239, 38245, 38249]),
 array([38245, 38249, 38259]),
 array([38249, 38259, 38810]),
 array([38259, 38810, 38991]),
 array([38810, 38991, 39001]),
 array([38991, 39001, 39002]),
 array([39001, 39002, 39011]),
 array([39002, 39011, 39021]),
 array([39011, 39021, 39102]),
 array([39021, 39102, 39204]),
 array([39102, 39204, 39244]),
 array([

In [66]:
predicted = nd.ContactPrediction(storage, 0.3)

In [67]:
predicted

[41102.0]

In [ ]:
#DC_DEF

In [47]:
predicted = []
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,34729, 120)
print(case_type, ":",duty_cycle)

1 : 8


In [ ]:
#DC_MAX

In [50]:
predicted = [34729.0]
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,34729, 120)
print(case_type, ":",duty_cycle)

2 : 20.0


In [ ]:
#DC_MIN

In [55]:
predicted = [34729.0]
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,10000, 1200)
print(case_type, ":",duty_cycle)

4 : 2


In [ ]:
#DC_SEREN

In [54]:
predicted = [20000, 30000]
case_type, duty_cycle = nd.DutyCycleAdaptation(predicted,25000, 5000)
print(case_type, ":",duty_cycle)

3 : 8.0
